[package]
name = "engine"
version = "0.1.0"
authors = ["rphmeier <rphmeier@gmail.com>"]

[dependencies]
libc = "*"
log = "*"

[features]
default = ["glutin"]

[dependencies.glutin]
version = "*"
optional = true